In [1]:
import numpy as np

a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
a = a[::-1]
print(a)

[10  9  8  7  6  5  4  3  2  1]


In [3]:
a = np.reshape(a,(2,5))
print(a)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [4]:
a = np.reshape(a,(5,2))
print(a)

[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]


In [5]:
import random

a = np.array([])

for i in range(10):
    a = np.append(a, np.random.random())
    
print('a =',a)
print('최댓값 :', max(a))
print('최솟값 :', min(a))
print('평균값 :', a.mean())

a = [0.60817534 0.0318628  0.54900507 0.38512083 0.11986228 0.24582547
 0.44059216 0.80953905 0.78517182 0.08852287]
최댓값 : 0.8095390542804469
최솟값 : 0.03186280440310996
평균값 : 0.4063677713267431


In [6]:
n = int(input('n을 입력하시오 : '))

arr1 = np.diag(1+np.arange(n))
print(arr1)

n을 입력하시오 : 5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [7]:
a = np.array([0, 10, 20, 40, 60, 80])
b = np.array([0, 20])

c = np.setdiff1d(a, b)

print('a 배열 : ', a)
print('b 배열 : ', b)
print('a - b :', c)

a 배열 :  [ 0 10 20 40 60 80]
b 배열 :  [ 0 20]
a - b : [10 40 60 80]


In [8]:
n = int(input('n을 입력하시오 : '))

m = np.ones((n,n), dtype=np.int8)
a = np.tril(m)
print(a)
print('행렬의 모든 원소의 합:',a.sum())
print('행렬의 행 방향 성분의 합:',a.sum(axis=0))
print('행렬의 열 방향 성분의 합:',a.sum(axis=1))

n을 입력하시오 : 5
[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]
행렬의 모든 원소의 합: 15
행렬의 행 방향 성분의 합: [5 4 3 2 1]
행렬의 열 방향 성분의 합: [1 2 3 4 5]


In [164]:
import pandas as pd

movies = pd.read_csv('C:/Users/Python/movies.csv')
movies = pd.DataFrame(movies)
print(movies[:10])
print(movies[-10:])

   Rank                         Title       Studio       Gross  Year
0     1             Avengers: Endgame  Buena Vista  $2,796.30   2019
1     2                        Avatar          Fox  $2,789.70   2009
2     3                       Titanic    Paramount  $2,187.50   1997
3     4  Star Wars: The Force Awakens  Buena Vista  $2,068.20   2015
4     5        Avengers: Infinity War  Buena Vista  $2,048.40   2018
5     6                Jurassic World    Universal  $1,671.70   2015
6     7         Marvel's The Avengers  Buena Vista  $1,518.80   2012
7     8                     Furious 7    Universal  $1,516.00   2015
8     9       Avengers: Age of Ultron  Buena Vista  $1,405.40   2015
9    10                 Black Panther  Buena Vista  $1,346.90   2018
     Rank                         Title           Studio     Gross  Year
772   773        Fun with Dick and Jane             Sony  $202.00   2005
773   774  Teenage Mutant Ninja Turtles         New Line  $202.00   1990
774   775             

In [10]:
print('행 개수 :', movies.shape[0])
print('열 개수 :', movies.shape[1])

행 개수 : 782
열 개수 : 5


In [11]:
movies.dtypes

Rank       int64
Title     object
Studio    object
Gross     object
Year       int64
dtype: object

In [12]:
movies.iloc[499]

Rank                              500
Title     Maze Runner: The Death Cure
Studio                            Fox
Gross                        $288.30 
Year                             2018
Name: 499, dtype: object

In [13]:
movies[movies['Title'].isin(['Forrest Gump'])]

Rank         Title     Studio     Gross  Year
118   119  Forrest Gump  Paramount  $677.90   1994

In [208]:
movies = movies.sort_values(by=['Year'])
print(movies[:10])

     Rank                               Title           Studio     Gross  Year
287   288                  Gone with the Wind              MGM  $402.40   1939
539   540                               Bambi              RKO  $267.40   1942
707   708                      101 Dalmatians      Buena Vista  $215.90   1961
754   755                     The Jungle Book      Buena Vista  $205.80   1967
603   604                       The Godfather        Paramount  $245.10   1972
251   252                        The Exorcist  Warner Brothers  $441.30   1973
227   228                                Jaws        Universal  $470.70   1975
451   452  Close Encounters of the Third Kind         Columbia  $306.90   1977
629   630                Saturday Night Fever        Paramount  $237.10   1977
90     91                           Star Wars              Fox  $775.40   1977


In [209]:
movies = movies.sort_values(by=['Studio', 'Year'], ascending=[True, False])
print(movies[-10:])

     Rank                    Title           Studio     Gross  Year
277   278                   Batman  Warner Brothers  $411.50   1989
659   660          Lethal Weapon 2  Warner Brothers  $227.90   1989
467   468                 Superman  Warner Brothers  $300.50   1978
251   252             The Exorcist  Warner Brothers  $441.30   1973
641   642       The Imitation Game        Weinstein  $233.60   2014
265   266         Django Unchained        Weinstein  $425.40   2012
264   265         The Intouchables        Weinstein  $426.60   2012
630   631  Silver Linings Playbook        Weinstein  $236.40   2012
275   276        The King's Speech        Weinstein  $414.20   2010
423   424     Inglourious Basterds        Weinstein  $321.50   2009


In [15]:
movies[(movies['Year']==2015) & (movies['Studio']=='Universal')]

Rank                   Title     Studio       Gross  Year
5       6          Jurassic World  Universal  $1,671.70   2015
18     19                 Minions  Universal  $1,159.40   2015
775   776  Straight Outta Compton  Universal    $201.60   2015
701   702                   Ted 2  Universal    $216.70   2015
765   766                 Everest  Universal    $203.40   2015
503   504         Pitch Perfect 2  Universal    $287.50   2015
164   165    Fifty Shades of Grey  Universal    $571.00   2015
7       8               Furious 7  Universal  $1,516.00   2015

In [16]:
movies[(movies['Year']==2015) | (movies['Studio']=='Universal')]

Rank                                       Title     Studio     Gross  \
227   228                                        Jaws  Universal  $470.70    
83     84                 E.T.: The Extra-Terrestrial  Universal  $792.90    
310   311                          Back to the Future  Universal  $381.10    
661   662                               Out of Africa  Universal  $227.50    
703   704                                       Twins  Universal  $216.60    
..    ...                                         ...        ...       ...   
491   492                        Pacific Rim Uprising  Universal  $290.90    
669   670                   The Secret Life of Pets 2  Universal  $225.90    
571   572                                          Us  Universal  $254.70    
590   591                                       Glass  Universal  $247.00    
198   199  How to Train Your Dragon: The Hidden World  Universal  $519.80    

     Year  
227  1975  
83   1982  
310  1985  
661  1985  
703  1988  
..    ...  
491  2018  
669  2019  
571  2019  
590  2019  
198  2019  

[140 rows x 5 columns]

In [17]:
movies[(movies['Year']<1975)]

Rank               Title           Studio     Gross  Year
287   288  Gone with the Wind              MGM  $402.40   1939
539   540               Bambi              RKO  $267.40   1942
707   708      101 Dalmatians      Buena Vista  $215.90   1961
754   755     The Jungle Book      Buena Vista  $205.80   1967
603   604       The Godfather        Paramount  $245.10   1972
251   252        The Exorcist  Warner Brothers  $441.30   1973

In [18]:
movies[(movies['Year']>1980) & (movies['Year']<1990)]

Rank                                 Title           Studio     Gross  \
299   300               Raiders of the Lost Ark        Paramount  $389.90    
83     84           E.T.: The Extra-Terrestrial        Universal  $792.90    
221   222                    Return of the Jedi              Fox  $475.10    
402   403  Indiana Jones and the Temple of Doom        Paramount  $333.10    
484   485                          Ghostbusters         Columbia  $295.20    
431   432                     Beverly Hills Cop        Paramount  $316.40    
310   311                    Back to the Future        Universal  $381.10    
466   467                              Rocky IV              MGM  $300.50    
661   662                         Out of Africa        Universal  $227.50    
468   469            Rambo: First Blood Part II          TriStar  $300.40    
356   357                               Top Gun        Paramount  $356.80    
412   413                      Crocodile Dundee        Paramount  $328.20    
427   428                      Fatal Attraction        Paramount  $320.10    
472   473                  Beverly Hills Cop II        Paramount  $300.00    
715   716                         Dirty Dancing          Vestron  $214.60    
495   496                     Coming to America        Paramount  $288.80    
622   623                   Crocodile Dundee II        Paramount  $239.60    
703   704                                 Twins        Universal  $216.60    
409   410               Who Framed Roger Rabbit      Buena Vista  $329.80    
360   361                              Rain Man              MGM  $354.80    
678   679              Honey, I Shrunk the Kids      Buena Vista  $222.70    
710   711                       Ghostbusters II         Columbia  $215.40    
405   406            Back to the Future Part II        Universal  $332.00    
635   636                    Dead Poets Society      Buena Vista  $235.90    
479   480                    Look Who's Talking          TriStar  $297.00    
224   225    Indiana Jones and the Last Crusade        Paramount  $474.20    
737   738                    The Little Mermaid      Buena Vista  $211.30    
277   278                                Batman  Warner Brothers  $411.50    
659   660                       Lethal Weapon 2  Warner Brothers  $227.90    

     Year  
299  1981  
83   1982  
221  1983  
402  1984  
484  1984  
431  1984  
310  1985  
466  1985  
661  1985  
468  1985  
356  1986  
412  1986  
427  1987  
472  1987  
715  1987  
495  1988  
622  1988  
703  1988  
409  1988  
360  1988  
678  1989  
710  1989  
405  1989  
635  1989  
479  1989  
224  1989  
737  1989  
277  1989  
659  1989

In [19]:
movies[movies['Title'].str.contains('dark', case=False)]

Rank                           Title           Studio       Gross  Year
38     39                 The Dark Knight  Warner Brothers  $1,004.90   2008
22     23  Transformers: Dark of the Moon        Paramount  $1,123.80   2011
599   600                    Dark Shadows  Warner Brothers    $245.50   2012
26     27           The Dark Knight Rises  Warner Brothers  $1,084.90   2012
131   132            Thor: The Dark World      Buena Vista    $644.60   2013
231   232         Star Trek Into Darkness        Paramount    $467.40   2013
308   309             Fifty Shades Darker        Universal    $381.50   2017
602   603                    Dark Phoenix              Fox    $245.10   2019

In [20]:
movies['Gross'].describe(include='object')

count          782
unique         701
top       $215.90 
freq             3
Name: Gross, dtype: object

In [64]:
movies["Gross"] = movies["Gross"].str.replace(pat=r'[^\w]', repl=r'', regex=True)
movies['Gross'] = pd.to_numeric(movies['Gross'])
groups = movies.groupby('Studio').sum()
print(groups['Gross'])

Studio
Artisan                     24860
Buena Vista               7358500
CL                          22810
China Film Corporation      69980
Columbia                   127660
Dimension                   48870
Dreamworks                1226040
FR                          38530
FUN                         35800
Focus                       20580
Fox                       5042080
GrtIndia                    25420
HC                          87030
IFC                         36870
Lions                       22240
Lionsgate                 1003320
MGM                        351310
Magn.                       20560
Miramax                    248060
New Line                   658480
Newmarket                   61190
Orion                       69690
Paramount                 3248600
Pathe                       24510
Polygram                    49690
RKO                         26740
Rela.                       22690
SonR                        51510
Sony                      3282250
TriStar

In [66]:
groups = groups.sort_values(by=['Gross'], ascending=False)
print(groups['Gross'][:10])

Studio
Buena Vista        7358500
Warner Brothers    5864380
Fox                5042080
Universal          4430230
Sony               3282250
Paramount          3248600
Dreamworks         1226040
Lionsgate          1003320
New Line            658480
MGM                 351310
Name: Gross, dtype: int64


In [67]:
s = pd.Series([1, 2, 3, np.nan, 4, 5])
s.sum()

15.0

In [69]:
s.sum(skipna = False)

nan

In [68]:
s.cumsum()

0     1.0
1     3.0
2     6.0
3     NaN
4    10.0
5    15.0
dtype: float64

In [70]:
s.cumsum(skipna = False)

0    1.0
1    3.0
2    6.0
3    NaN
4    NaN
5    NaN
dtype: float64

In [73]:
print('평균 :',s.mean())
print('분산 :',s.var())
print('최댓값 :',s.max())
print('최솟값 :',s.min())

평균 : 3.0
분산 : 2.5
최댓값 : 5.0
최솟값 : 1.0


In [ ]:
google = pd.read_csv("C:/Users/Python/google_stocks.csv", index_col = "Date", squeeze = True)
google.index = pd.to_datetime(google.index, format='%Y-%m-%d')

In [202]:
google = pd.Series(google)
print(google)

Date
2004-08-19      49.98
2004-08-20      53.95
2004-08-23      54.50
2004-08-24      52.24
2004-08-25      52.80
               ...   
2019-10-21    1246.15
2019-10-22    1242.80
2019-10-23    1259.13
2019-10-24    1260.99
2019-10-25    1265.13
Name: Close, Length: 3824, dtype: float64


In [203]:
google = google.sort_values(ascending=False)
print(google[:5])
google = google.sort_values(ascending=True)
print(google[:5])

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64
Date
2004-09-03    49.82
2004-09-01    49.94
2004-08-19    49.98
2004-09-02    50.57
2004-09-07    50.60
Name: Close, dtype: float64


In [204]:
freq = google.value_counts() 
print(freq)

194.27    3
307.10    3
237.04    3
287.68    3
290.41    3
         ..
288.10    1
964.86    1
144.96    1
290.92    1
306.65    1
Name: Close, Length: 3696, dtype: int64


In [207]:
bins = [0, 200, 400, 600, 800, 1000, 1200, 1400]
google.value_counts(bins = bins).sort_index()

(-0.001, 200.0]      595
(200.0, 400.0]      1568
(400.0, 600.0]       575
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1000.0, 1200.0]     406
(1200.0, 1400.0]      93
Name: Close, dtype: int64

In [182]:
grouped = pd.qcut(google, 6)
pd.Series(grouped).value_counts(sort = False).sort_index()

(49.819, 203.272]     638
(203.272, 261.963]    637
(261.963, 314.68]     637
(314.68, 548.793]     637
(548.793, 845.607]    637
(845.607, 1287.58]    638
Name: Close, dtype: int64

In [211]:
import datetime as dt
def day_of_week(date):
    return date.strftime("%A")

days_of_war = pd.read_csv('C:/Users/Python/revolutionary_war.csv', usecols = ["Start Date"],
                         parse_dates = ["Start Date"], squeeze = True)
days_of_war = days_of_war.dropna().apply(day_of_week)
print(days_of_war)

0       Thursday
1      Wednesday
2      Wednesday
3      Wednesday
4       Thursday
         ...    
227    Wednesday
228       Friday
229       Friday
230       Friday
231    Wednesday
Name: Start Date, Length: 228, dtype: object


In [200]:
days_of_war.value_counts()

Saturday     39
Friday       39
Wednesday    32
Thursday     31
Sunday       31
Tuesday      29
Monday       27
Name: Start Date, dtype: int64