In [7]:
import numpy as np #11.4

a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
a = a[::-1]
print(a)

[10  9  8  7  6  5  4  3  2  1]


In [10]:
a = np.reshape(a,(2,5))
print(a)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [11]:
a = np.reshape(a,(5,2))
print(a)

[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]


In [31]:
import random #11.6

a = np.array([])

for i in range(10):
    a = np.append(a, np.random.random())
    
print('a =',a)
print('최댓값 :', max(a))
print('최솟값 :', min(a))
print('평균값 :', a.mean())

a = [0.29305486 0.76184222 0.75072086 0.27923228 0.21818679 0.60287734
 0.9255267  0.72345892 0.24705305 0.25473384]
최댓값 = 0.9255266993821754
최솟값 = 0.21818679351746662
최댓값 = 0.505668686237706


In [34]:
n = int(input('n을 입력하시오 : ')) #11.8

arr1 = np.diag(1+np.arange(n))
print(arr1)

n을 입력하시오 : 5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [37]:
a = np.array([0, 10, 20, 40, 60, 80]) #11.13
b = np.array([0, 20])

c = np.setdiff1d(a, b)

print('a 배열 : ', a)
print('b 배열 : ', b)
print('a - b :', c)

a 배열 :  [ 0 10 20 40 60 80]
b 배열 :  [ 0 20]
a - b : [10 40 60 80]


In [90]:
n = int(input('n을 입력하시오 : ')) #11.15

m = np.ones((n,n), dtype=np.int8)
a = np.tril(m)
print(a)
print('행렬의 모든 원소의 합:',a.sum())
print('행렬의 행 방향 성분의 합:',a.sum(axis=0))
print('행렬의 열 방향 성분의 합:',a.sum(axis=1))

n을 입력하시오 : 5
[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]
행렬의 모든 원소의 합: 15
행렬의 행 방향 성분의 합: [5 4 3 2 1]
행렬의 열 방향 성분의 합: [1 2 3 4 5]


In [100]:
import pandas as pd

movies = pd.read_csv('C:/Users/Python/movies.csv')
movies = pd.DataFrame(movies)
print(movies[:10])
print(movies[-10:])

   Rank                         Title       Studio       Gross  Year
0     1             Avengers: Endgame  Buena Vista  $2,796.30   2019
1     2                        Avatar          Fox  $2,789.70   2009
2     3                       Titanic    Paramount  $2,187.50   1997
3     4  Star Wars: The Force Awakens  Buena Vista  $2,068.20   2015
4     5        Avengers: Infinity War  Buena Vista  $2,048.40   2018
5     6                Jurassic World    Universal  $1,671.70   2015
6     7         Marvel's The Avengers  Buena Vista  $1,518.80   2012
7     8                     Furious 7    Universal  $1,516.00   2015
8     9       Avengers: Age of Ultron  Buena Vista  $1,405.40   2015
9    10                 Black Panther  Buena Vista  $1,346.90   2018
     Rank                         Title           Studio     Gross  Year
772   773        Fun with Dick and Jane             Sony  $202.00   2005
773   774  Teenage Mutant Ninja Turtles         New Line  $202.00   1990
774   775             

In [103]:
print('행 개수 :', movies.shape[0])
print('열 개수 :', movies.shape[1])

행 개수 : 782
열 개수 : 5
